# Generated by Django 4.2.29 on 2026-03-24 08:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Media Library",
                "verbose_name_plural": "Media Libraries",
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "song_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_file_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Actual duration of the generated audio track.",
                        null=True,
                    ),
                ),
                ("is_favorited", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "Generating"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="GENERATING",
                        max_length=20,
                    ),
                ),
                (
                    "media_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="generator.medialibrary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
                "ordering": ["-creation_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(max_length=255, unique=True)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("onboarding_status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="SongProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("WORKOUT", "Workout"),
                            ("STUDY", "Study"),
                            ("PARTY", "Party"),
                            ("COMMUTE", "Commute"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("POP", "Pop"),
                            ("J_POP", "J-Pop"),
                            ("JDM", "JDM"),
                            ("ROCK", "Rock"),
                            ("ELECTRONIC", "Electronic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("ENERGETIC", "Energetic"),
                            ("CALMING", "Calming"),
                            ("UPBEAT", "Upbeat"),
                            ("SAD", "Sad"),
                            ("DREAMY", "Dreamy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vocal_selection",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("INSTRUMENTAL", "Instrumental"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requested_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Desired song length in seconds (120–360 s / 2–6 minutes).",
                        null=True,
                    ),
                ),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_profile",
                        to="generator.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "Song Profile",
                "verbose_name_plural": "Song Profiles",
            },
        ),
        migrations.CreateModel(
            name="SharedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_url",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID-backed unique share token used to build the share URL.",
                        unique=True,
                    ),
                ),
                (
                    "allow_download",
                    models.BooleanField(
                        default=False,
                        help_text="If True, authenticated recipients may download the MP3 (FR-22).",
                    ),
                ),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_link",
                        to="generator.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Link",
                "verbose_name_plural": "Shared Links",
            },
        ),
        migrations.AddField(
            model_name="medialibrary",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_library",
                to="generator.user",
            ),
        ),
    ]
