# Generated by Django 4.2.29 on 2026-04-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="generation_task_id",
            field=models.CharField(
                blank=True,
                help_text="Task ID returned by the generation strategy (mock or Suno API).",
                max_length=255,
                null=True,
            ),
        ),
    ]
