# Generated by Django 4.2.29 on 2026-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_song_generation_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album_art_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to the album art/cover image from Suno API.",
                max_length=2048,
            ),
        ),
    ]
